image: gitlab.e1c.net:4567/ops/runners:node6

before_script:
  - rm -rf ci-config
  - git clone git@gitlab.e1c.net:ops/ci-config

stages:
  - test
  - semver
  - sinopia

runTests:
  stage: test
  except:
    - tags
  script:
    - ./ci-config/build.sh test

semverBump:
  stage: semver
  only:
    - develop
  script:
    - ./ci-config/build.sh semver

sinopia:
  stage: sinopia
  only:
    - develop
  script:
    - ./ci-config/build.sh sinopia
