# Execute on the Node6 runner
image: gitlab.e1c.net:4567/ops/runners:node6

stages:
  - test
  - increment-version
  - publish-npm-package

# Grab the helper scripts, and make sure variables are set
before_script:
  - git clone --depth 1 git@gitlab.e1c.net:ops/ci-scripts.git
  - source ci-scripts/set-variables.sh

test:
  stage: test
  script:
    - npm i
    - npm run test

increment-version:
  stage: increment-version
  only:
    - develop@evs/service-logger
  script:
    - ci-scripts/increment-version.sh

publish-npm-package:
  stage: publish-npm-package
  only:
    - develop@evs/service-logger
  script:
    - ./ci-scripts/publish-npm-package.sh